---

 - name: Creates directory
   file: path={{ consul_parent_dir }} state=directory

 - name: Creates config directory
   file: path={{ consul_parent_dir }}/config  state=directory

 - unarchive:
     src: "{{ consul_binary }}"
     dest: "{{ consul_parent_dir }}"

 - name: Add consul config file
   template: src=client.json.j2 dest={{ consul_parent_dir }}/config/client.json

 - name:
   shell: nohup {{ consul_parent_dir }}/consul agent --config-dir={{ consul_parent_dir }}/config >{{ consul_parent_dir }}/consul.out&

