---

 - name: Creates directory
   file: path={{ consul_parent_dir }} state=directory

 - name: Creates data directory
   file: path={{ data_dir }}  state=directory

 - name: Creates config directory
   file: path={{ consul_parent_dir }}/config  state=directory

 - unarchive:
     src: "{{ consul_binary }}"
     dest: "{{ consul_parent_dir }}"

 - name: Add consul config file
   template: src=server.json.j2 dest={{ consul_parent_dir }}/config/server.json

 - name:
   shell: nohup /opt/consul/consul agent -ui --config-dir={{ consul_parent_dir }}/config >{{ consul_parent_dir }}/consul.out&

